packages:
  - packages/*

onlyBuiltDependencies:
  - core-js
  - unrs-resolver

catalog:
  '@antfu/eslint-config': ^4.13.0
  '@antfu/install-pkg': ^1.0.0
  '@clack/prompts': ^0.10.1
  '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
  '@eslint-react/eslint-plugin': ^1.48.4
  '@eslint/markdown': ^6.4.0
  '@rslib/core': ^0.6.7
  '@stylistic/eslint-plugin': ^4.2.0
  '@tanstack/eslint-plugin-query': ^5.73.3
  '@tanstack/eslint-plugin-router': ^1.115.0
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.14.1
  '@typescript-eslint/eslint-plugin': ^8.31.0
  '@typescript-eslint/parser': ^8.31.0
  eslint: ^9.25.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-flat-config-utils: ^2.0.1
  eslint-merge-processors: ^2.0.0
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-command: ^3.2.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import-x: ^4.10.6
  eslint-plugin-jsdoc: ^50.6.10
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-n: ^17.17.0
  eslint-plugin-perfectionist: ^4.12.2
  eslint-plugin-pnpm: ^0.3.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: ^58.0.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: latest
  eslint-plugin-vue-router: latest
  eslint-plugin-vuejs-accessibility: ^2.4.1
  eslint-plugin-yml: ^1.18.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^2.1.0
  globals: ^16.0.0
  jsonc-eslint-parser: ^2.4.0
  local-pkg: ^1.1.1
  lodash-es: ^4.17.21
  toml-eslint-parser: ^0.10.0
  tsx: ^4.19.4
  typescript: ^5.8.3
  vue-eslint-parser: ^10.1.3
  yaml-eslint-parser: ^1.3.0
